---
- name: Stop Cribl Edge service
  ansible.builtin.systemd:
    name: cribl-edge
    state: stopped
    enabled: no

- name: Uninstall Cribl Edge
  ansible.builtin.package:
    name: cribl-edge
    state: absent

- name: Remove Cribl Edge data directory
  ansible.builtin.shell: rm -rf /opt/cribl

- name: Remove cribl user
  ansible.builtin.user:
    name: cribl
    state: absent
    remove: yes

- name: Remove cribl group
  ansible.builtin.group:
    name: cribl
    state: absent

