---
galaxy_info:
  role_name: ansible_cribl_edge
  author: Chad Zimmerman
  description: An Ansible Role that will Install Cribl Edge
  company: ''
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "38"
        - "39"
        - "40"
        - "41"
    - name: Debian
      versions:
        - "bookworm"
        - "bullseye"
    - name: Ubuntu
      versions:
        - "noble"
        - "jammy"
        - "focal"
  galaxy_tags:
    - linux
    - observability

dependencies: []

collections: []
