---
- name: Install Cribl Edge | Linux
  ansible.builtin.import_tasks: install_cribl_linux.yml
  when:
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'RedHat'
  tags: install

- name: Uninstall Cribl Edge | Linux
  ansible.builtin.import_tasks: uninstall_cribl_linux.yml
  when:
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'RedHat'
  tags: uninstall
