---
- name: Stop Cribl Edge service
  ansible.builtin.systemd:
    name: cribl-edge
    state: stopped
    enabled: no
  ignore_errors: true # If the package is not installed, this will fail

- name: Uninstall Cribl Edge
  ansible.builtin.package:
    name: cribl-edge
    state: absent
  ignore_errors: true # If the package is not installed, this will fail

- name: Remove Cribl Edge data directory
  ansible.builtin.file:
    path: /opt/cribl
    state: absent
    recurse: yes

- name: Remove Cribl Edge Systemd Unit File
  ansible.builtin.file:
    path: /etc/systemd/system/cribl-edge.service
    state: absent

- name: Reload Systemd Daemons
  ansible.builtin.systemd:
    daemon_reload: true

- name: Remove cribl user
  ansible.builtin.user:
    name: "{{ cribl_edge_user }}"
    state: absent
    remove: true
  when: cribl_edge_user != 'root'

- name: Remove cribl group
  ansible.builtin.group:
    name: "{{ cribl_edge_group }}"
    state: absent
  when: cribl_edge_user != 'root'
